[2023-07-23T20:32:38.064+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_load_university_data.loading_dbo manual__2023-07-23T20:27:19.368671+00:00 [queued]>
[2023-07-23T20:32:38.087+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_load_university_data.loading_dbo manual__2023-07-23T20:27:19.368671+00:00 [queued]>
[2023-07-23T20:32:38.087+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-23T20:32:38.115+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): loading_dbo> on 2023-07-23 20:27:19.368671+00:00
[2023-07-23T20:32:38.129+0000] {standard_task_runner.py:57} INFO - Started process 2394 to run task
[2023-07-23T20:32:38.135+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'daily_load_university_data', 'loading_dbo', 'manual__2023-07-23T20:27:19.368671+00:00', '--job-id', '333', '--raw', '--subdir', 'DAGS_FOLDER/LoadInitiator.py', '--cfg-path', '/tmp/tmp8s7au9k5']
[2023-07-23T20:32:38.139+0000] {standard_task_runner.py:85} INFO - Job 333: Subtask loading_dbo
[2023-07-23T20:32:38.200+0000] {task_command.py:410} INFO - Running <TaskInstance: daily_load_university_data.loading_dbo manual__2023-07-23T20:27:19.368671+00:00 [running]> on host 3906890fc071
[2023-07-23T20:32:38.301+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_load_university_data' AIRFLOW_CTX_TASK_ID='loading_dbo' AIRFLOW_CTX_EXECUTION_DATE='2023-07-23T20:27:19.368671+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-23T20:27:19.368671+00:00'
[2023-07-23T20:32:38.348+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-07-23T20:32:38.350+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/dags/LoadDbo.py']
[2023-07-23T20:32:38.394+0000] {subprocess.py:86} INFO - Output:
[2023-07-23T20:32:38.875+0000] {subprocess.py:93} INFO - WARNING:root:Connection established to Postgres succussfully!....
[2023-07-23T20:32:38.922+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-07-23T20:32:38.954+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=daily_load_university_data, task_id=loading_dbo, execution_date=20230723T202719, start_date=20230723T203238, end_date=20230723T203238
[2023-07-23T20:32:38.988+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-23T20:32:39.008+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
